routes/web.php
<?php

use App\Http\Controllers\Admin\ConfigurationController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Front\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware(['auth']);

Route::middleware(['auth', 'available'])->name('front.')->group(function () {
    Route::get('quiz', [DashboardController::class, 'getQuiz'])->name('quiz');
});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    Route::get('/questions/data', [QuestionController::class, 'data'])->name('questions.data');
    Route::resource('questions', QuestionController::class);

    Route::get('/configurations', [ConfigurationController::class, 'index'])->name('configurations.index');
    Route::put('/configurations/{id}', [ConfigurationController::class, 'update'])->name('configurations.update');
});

require __DIR__.'/auth.php';

app/Models/Configuration.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Configuration extends Model
{
    public $guarded = ['id'];
}

app/Http/Controllers/Admin/ConfigurationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Configuration;
use Illuminate\Http\Request;

class ConfigurationController extends Controller
{
    public function __construct()
    {
        $this->middleware(function($request, $next) {
            if (auth()->user()->is_admin !== 1){
                abort('404');
            }
            return $next($request);
        });
    }

    public function index()
    {
        $configuration = Configuration::first();

        return view('admin.configurations.index', compact('configuration'));
    }

    public function update(Request $request, $id)
    {
        $configuration = Configuration::find($id);

        $configuration->questions_per_day = $request->questions_per_day;
        $configuration->coins_per_correct_ans = $request->coins_per_correct_ans;
        $configuration->hours_for_next_questions = $request->hours_for_next_questions;

        $configuration->save();

        return redirect(route('admin.configurations.index'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/configurations/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <a class="mr-20" href="{{route('admin.questions.index')}}">Quiz Questions</a>
            <a href="{{route('admin.configurations.index')}}">Configurations</a>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form action="{{ route('admin.configurations.update', $configuration->id) }}" method="post">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label for="qpd">Questions Per Day</label>
                            <input class="rounded mb-5" type="text" name="questions_per_day" id="qpd" value="{{ $configuration->questions_per_day }}" />
                        </div>

                        <div class="form-group">
                            <label for="cpca">Coins Per Correct Answer</label>
                            <input class="rounded mb-5" type="text" name="coins_per_correct_ans" id="cpca" value="{{ $configuration->coins_per_correct_ans }}" />
                        </div>

                        <div class="form-group">
                            <label for="hfnq">Hours for Next Question Set</label>
                            <input class="rounded mb-5" type="text" name="hours_for_next_questions" id="hfnq" value="{{ $configuration->hours_for_next_questions }}" />
                        </div>

                        <button class="bg-blue-500 text-white p-3" type="submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>