routes/web.php
<?php

use App\Http\Controllers\Admin\ConfigurationController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Front\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware(['auth']);

Route::middleware(['auth', 'available'])->name('front.')->group(function () {
    Route::get('quiz', [DashboardController::class, 'getQuiz'])->name('quiz');
});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    Route::get('/questions/data', [QuestionController::class, 'data'])->name('questions.data');
    Route::resource('questions', QuestionController::class);

    Route::get('/configurations', [ConfigurationController::class, 'index'])->name('configurations.index');
    Route::put('/configurations/{id}', [ConfigurationController::class, 'update'])->name('configurations.update');
});

require __DIR__.'/auth.php';

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $guarded = ['id'];

    protected $casts = [
        'options' => 'array'
    ];
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Questions\StoreRequest;
use App\Http\Requests\Questions\UpdateRequest;
use App\Models\Question;
use App\Models\User;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class QuestionController extends Controller
{
    public function __construct()
    {
        $this->middleware(function($request, $next) {
            if (auth()->user()->is_admin !== 1){
                abort('404');
            }
            return $next($request);
        });
    }

    public function index()
    {
        return view('admin.questions.index');
    }

    public function create()
    {
        $view = view('admin.partials.add-question')->render();

        return response(['html' => $view]);
    }

    public function store(StoreRequest $request)
    {
        $question = new Question();

        $optionArr = [
            'a' => $request->option1,
            'b' => $request->option2,
            'c' => $request->option3,
            'd' => $request->option4,
        ];

        $question->question = $request->question;
        $question->options = $optionArr;
        $question->correct_answer = $request->correct_ans;

        $question->save();

        return redirect(route('admin.questions.index'));
    }

    public function edit($id)
    {
        $question = Question::findOrFail($id);

        $view = view('admin.partials.edit-question', compact('question'))->render();

        return response(['html' => $view]);
    }

    public function update(UpdateRequest $request, $id)
    {
        $question = Question::findOrFail($id);

        $optionArr = [
            'a' => $request->option1,
            'b' => $request->option2,
            'c' => $request->option3,
            'd' => $request->option4,
        ];

        $question->question = $request->question;
        $question->options = $optionArr;
        $question->correct_answer = $request->correct_ans;

        $question->save();

        return redirect(route('admin.questions.index'));
    }

    public function destroy($id)
    {
        Question::destroy($id);

        return response([]);
    }

    public function data()
    {
        $questions = Question::all();
        // $questions = User::all();

        return DataTables::of($questions)
                        ->addIndexColumn()
                        ->addColumn('actions', function ($row)
                        {
                            $actions = "<a href='javascript:editQuestion(".$row->id.");'>Edit</a> <a href='javascript:deleteQuestion(".$row->id.");'>Delete</a>";
                            return $actions;
                        })
                        ->addColumn('question', function ($row) {
                            return $row->question;
                        })
                        ->addColumn('options', function ($row) {
                            $options = '<ul>';
                            foreach ($row->options as $key => $value) {
                                $options .= '<li>'.$key.':'.$value.'</li>';
                            }
                            $options .= '</ul>';
                            return $options;
                        })
                        ->addColumn('correct_answer', function ($row) {
                            return $row->correct_answer;
                        })
                        ->rawColumns(['actions', 'options'])
                        ->make(true);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/questions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <a class="mr-20" href="{{route('admin.questions.index')}}">Quiz Questions</a>
            <a href="{{route('admin.configurations.index')}}">Configurations</a>
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <button class="p-2 m-2 border border-gray-200" onclick="javascript:addQuestion();">Add New</button>
                    <div id="add-edit-form">
                        @include('admin.partials.add-question')
                    </div>
                    <table class="table table-bordered" id="users-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Question</th>
                                <th>Options</th>
                                <th>Correct Answer</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            var usersTable;
            // $(function() {
                usersTable = $('#users-table').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: "{!! route('admin.questions.data') !!}",
                    columns: [
                        { data: 'id', name: 'id' },
                        { data: 'question', name: 'question' },
                        { data: 'options', name: 'options' },
                        { data: 'correct_answer', name: 'correct_answer' },
                        { data: 'actions', name: 'actions' }
                    ]
                });
            // });

            function addQuestion() {
                var url = "{{ route('admin.questions.create') }}"

                $.ajax({
                    url,
                    success: function (data) {
                        $('#add-edit-form').html(data.html)
                    }
                })
            }

            function editQuestion(id) {
                var url = "{{ route('admin.questions.edit', ':id') }}"
                url = url.replace(':id', id)

                $.ajax({
                    url,
                    success: function (data) {
                        $('#add-edit-form').html(data.html)
                    }
                })
            }

            function deleteQuestion(id) {
                var url = "{{ route('admin.questions.destroy', ':id') }}"
                url = url.replace(':id', id)

                $.ajax({
                    url,
                    type: 'POST',
                    data: {
                        _token: '{{ csrf_token() }}',
                        _method: 'DELETE'
                    },
                    success: function (data) {
                        usersTable.draw()
                    }
                })
            }
        </script>
    @endpush
</x-app-layout>