routes/web.php
<?php

use App\Http\Controllers\Admin\ConfigurationController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Front\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard')->middleware(['auth']);

Route::middleware(['auth', 'available'])->name('front.')->group(function () {
    Route::get('quiz', [DashboardController::class, 'getQuiz'])->name('quiz');
});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    Route::get('/questions/data', [QuestionController::class, 'data'])->name('questions.data');
    Route::resource('questions', QuestionController::class);

    Route::get('/configurations', [ConfigurationController::class, 'index'])->name('configurations.index');
    Route::put('/configurations/{id}', [ConfigurationController::class, 'update'])->name('configurations.update');
});

require __DIR__.'/auth.php';

resources/views/admin/partials/add-question.blade.php
<form class="m-3 p-3 border" action="{{ route('admin.questions.store') }}" method="post">
    @csrf
    <h2>Add New Question</h2>
    <div class="m-3">
        <label for="question">Question</label>
        <input type="text" name="question" id="question">
    </div>
    <div class="m-3">
        <label for="options">Options</label>
        <input type="text" name="option1" id="option1">
        <input type="text" name="option2" id="option2">
        <input type="text" name="option3" id="option3">
        <input type="text" name="option4" id="option4">
    </div>
    <div class="m-3">
        <label for="correct-ans">Correct Option</label>
        <input type="text" name="correct_ans" id="correct_ans">
    </div>
    <button class="p-2 rounded bg-blue-500 text-white">Save</button>
</form>

resources/views/admin/partials/edit-question.blade.php
<form class="m-3 p-3 border" action="{{ route('admin.questions.update', $question->id) }}" method="post">
    @csrf
    @method('PUT')
    <h2>Edit Question</h2>
    <div class="m-3">
        <label for="question">Question</label>
        <input type="text" name="question" id="question" value="{{ $question->question }}">
    </div>
    <div class="m-3">
        <label for="options">Options</label>
        <input type="text" name="option1" id="option1" value="{{ $question->options['a'] }}">
        <input type="text" name="option2" id="option2" value="{{ $question->options['b'] }}">
        <input type="text" name="option3" id="option3" value="{{ $question->options['c'] }}">
        <input type="text" name="option4" id="option4" value="{{ $question->options['d'] }}">
    </div>
    <div class="m-3">
        <label for="correct-ans">Correct Option</label>
        <input type="text" name="correct_ans" id="correct_ans" value="{{ $question->correct_answer }}">
    </div>
    <button class="p-2 rounded bg-blue-500 text-white">Update</button>
</form>